---
- name: MINECRAFTSERVER
  hosts: minecraft_server
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
  - name: apt update
    raw: apt update
  - name: install docker
    raw: snap install docker
  - name: install minecraft container
    raw: docker run -d --restart=always -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
